apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  labels:
    build: foobar
  name: foobar
  namespace: s2i-test
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: foobar:latest
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
